// <auto-generated />
using System;
using CTVoicer.Veiculos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTVoicer.Veiculos.Data.Migrations
{
    [DbContext(typeof(VeiculoContext))]
    [Migration("20210709152324_CorrecaoCampoChassi")]
    partial class CorrecaoCampoChassi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CTVoicer.Veiculos.Bussiness.Models.Cor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Cor");
                });

            modelBuilder.Entity("CTVoicer.Veiculos.Bussiness.Models.TipoVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("QuantidadePassageiros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoVeiculo");
                });

            modelBuilder.Entity("CTVoicer.Veiculos.Bussiness.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("CorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TipoVeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorId");

                    b.HasIndex("TipoVeiculoId");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("CTVoicer.Veiculos.Bussiness.Models.Veiculo", b =>
                {
                    b.HasOne("CTVoicer.Veiculos.Bussiness.Models.Cor", "Cor")
                        .WithMany()
                        .HasForeignKey("CorId")
                        .IsRequired();

                    b.HasOne("CTVoicer.Veiculos.Bussiness.Models.TipoVeiculo", "TipoVeiculo")
                        .WithMany()
                        .HasForeignKey("TipoVeiculoId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
